import { StyleSheet } from 'react-native';
import { red } from 'react-native-reanimated/lib/typescript/Colors';

const styles = StyleSheet.create({
    background: {
      width: '100%',
      minHeight: '100%',
    },
    titleContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    stepContainer: {
      gap: 8,
      marginBottom: 8,
    },
    content: {
        flex: 1,
        padding: 32,
        gap: 16,
        overflow: 'hidden',
        backgroundColor: '#F3F7FF',
        position: 'relative',
    },
    contentColorLess: {
      flex: 1,
      padding: 32,
      gap: 16,
      overflow: 'hidden',
      position: 'relative',
    },
    button: {
        height: 50,
        width: 50,
        backgroundColor: '#5D63D1',
        borderRadius: 15,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        color: '#fff',
    },
    reactLogo: {
      height: '100%',
      width: '100%',
      bottom: 0,
      left: 0,
      position: 'absolute',
      borderRadius: 15,
      objectFit: 'cover',
    },
    widgetArea: {
      width: '100%',
      minHeight: 50,
      padding: 16,
      borderRadius: 15,
      boxShadow: '0 0 8px 0 rgba(0,0,0,0.2)',
      shadowOpacity: 0.5,
      shadowRadius: 3,
      backgroundColor: '#fff',
      display: 'flex',
    },
    widgetSession: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: '#5D63D1',
    },
    widgetSessionColumn: {
      display: 'flex',
      flexDirection: 'column',
      height: '100%',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
    },
    widgetSessionIcon:{
      justifyContent: 'center',
      backgroundColor: '#6D73DF',
      borderRadius: '100%',
      height: 50,
      width: 50,
    },

    runningScreen:{
        flex: 1,
        height: '100%',
        minHeight: '100%',
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
        position: 'relative',
    },
    runningInterfaces: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
        position: 'relative',
        zIndex: 100,
    },
    runningHeader:{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        zIndex: 100,
    },
    runningMap:{
        height: '100%',
        width: '100%',
        backgroundColor: 'blue',
        position: 'absolute',
        zIndex: 1,
        top: 0,
    },
    runningData:{
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    runningDataPart: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        height: '50%',
    },
    runningDataHeaderLeft: {
        display: 'flex',
        flexDirection: 'column',
        // justifyContent: 'space-between',
        alignItems: 'flex-start',
        height: '100%',
    },
    runningDataBottom: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      backgroundColor: '#F3F7FF',
      borderRadius: 15,
      gap: 8,
    },
    runningDataCol:{
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '30%',
      padding: 8,
    },
    runningBorderRight:{
      borderRightColor: '#333333',
      borderRightWidth: 1,
    },
    runningDataColitem:{
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'flex-start',
      alignItems: 'flex-end',
    }
});

export default styles;